dssd/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/stock/', include('dssd_app.urls')),
    path('api/rrhh/', include('dssd_rrhh.urls')),
    path('api/coupons/', include('dssd_coupon.urls')),
    path('web/', include('dssd_web.urls')),
]

urlpatterns += [
    path('api/v1/auth', include('rest_framework.urls', namespace='rest_framework'))
]

dssd_app/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from dssd_app.views import *

app_name = "dssd_app"

urlpatterns = [

    # URLs de los Productos de Stock
    url(r'^product/$', ProductList.as_view(), name='list_products'),
    url(r'^product/(?P<pk>[0-9]+)/$', ProductDetail.as_view(), name='details_product'),

    # URLs de los Tipos de Productos del Stock
    url(r'^product-types/$', ProductTypeList.as_view(), name='list_product_types'),
    url(r'^product-types/(?P<pk>[0-9]+)/$', ProductTypeDetail.as_view(), name='details_product_type'),

    # URLs para lo relacionado a las ventas
    url(r'^sales/$', SaleList.as_view(), name='list_sales'),
    url(r'^sales/(?P<pk>[0-9]+)/$', SaleDetail.as_view(), name='details_sale'),
    url(r'^sales/add/$', add_sale, name='add_sale'),
    url(r'^sales/get-coupon-discount/$', get_coupon_discount_view, name='get_coupon_discount'),
    url(r'^sales/get-discount/$', get_discount_view, name='get_discount')
]
urlpatterns = format_suffix_patterns(urlpatterns)

dssd_web/urls.py
from django.conf.urls import url
from .views import home_action, login_action, authenticate_action, logout_action, statistics_action

urlpatterns = [
    url(r'^$', home_action, name="index"),
    url(r'^login$', login_action, name="login"),
    url(r'^authenticate$', authenticate_action, name="authenticate"),
    url(r'^logout', logout_action, name="logout"),
    url(r'^statistics', statistics_action, name="statistics"),
]

dssd_web/models.py
from django.db import models

# Create your models here.

dssd_web/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def home_action(request):
    """Renderiza el template del index"""
    return render(request, 'dssd_web/index.html')


@login_required
def statistics_action(request):
    """Renderiza el template de los graficos estadisticos"""
    return render(request, 'dssd_web/statistics.html')


def login_action(request):
    """Rederiza el template del login"""
    # Si esta logueado redirige al index
    if request.user.is_authenticated:
        return redirect('index')

    return render(request, 'dssd_web/login.html')


def authenticate_action(request):
    """Valida la autenticacion de un usuario"""
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('index')
    else:
        return render(request, 'dssd_web/login.html', {
            'error_message': 'Usuario o password inválida'
        })


def logout_action(request):
    """Cierra la sesion de un usuario"""
    logout(request)
    return render(request, 'dssd_web/login.html')

dssd_web/templates/dssd_web/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SuperMercado ChangoMas</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {# Necesario para que se adapte Bootstrap #}

    {# CSS general #}
    <link href="{% static "dssd_web/bootstrap-3.3.7/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "dssd_web/bundles/base.css" %}" rel="stylesheet">

    {# Estilos particulares de cada pagina#}
    {% block styles %}{% endblock %}
</head>
<body>
    {# Contenido particular de cada pagina #}
    {% block content %}{% endblock %}

    {# JS general #}
    <script src="{% static "dssd_web/bundles/base.js" %}"></script>

    {# URLs dinamicas #}
    <script>
        {# Cookie de la session #}
        const cookieSessionId = "{{ request.COOKIES.sessionid }}";

        {# URLs #}
        const getProductsURL = "{% url 'dssd_app:list_products' %}"; {# URL para obtener los productos #}
        const indexURL = "{% url 'index' %}"; {# URL del index #}
        const loginURL = "{% url 'login' %}"; {# URL del login #}
        const logoutURL = "{% url 'logout' %}"; {# URL para cerrar sesion #}
        const buyURL = "{% url 'dssd_app:add_sale' %}"; {# URL para confirmar la compra #}
        const getGeneralDicountURL = "{% url 'dssd_app:get_discount' %}"; {# URL para obtener el descuento general #}
        const getCouponDicountURL = "{% url 'dssd_app:get_coupon_discount' %}"; {# URL para obtener el descuento por el cupon ingresado #}

        {% if user.is_authenticated %}
            const isAuthenticated = true; {# Booleano para ver si esta logueado actualmente #}
            const statisticsURL = "{% url 'statistics' %}"; {# URL de los graficos estadisticos #}
        {% else %}
            const isAuthenticated = false; {# Booleano para ver si esta logueado actualmente #}
            const statisticsURL = ""; {# URL de los graficos estadisticos #}
        {% endif %}
    </script>

    {# Scripts particulares de cada pagina #}
    {% block scripts %}{% endblock %}
</body>
</html>

dssd_web/templates/dssd_web/index.html
{% extends 'dssd_web/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static "dssd_web/bundles/index.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
    {# App principal, renderizada con React #}
    <div id="app"></div>
{% endblock %}

{% block scripts %}
    {# Script generado por webpack #}
    <script src="{% static "dssd_web/bundles/index.js" %}"></script>
{% endblock %}

dssd_web/templates/dssd_web/login.html
{% extends 'dssd_web/base.html' %}
{% load static %}

{% block styles %}
    <link href="{% static "dssd_web/css/login.css" %}" rel="stylesheet">
{% endblock %}


{% block content %}
     <div id="login-form">
        <div class="row">
            <div class="col-md-12 text-center">
                <img id="login-icon" src="{% static "dssd_web/img/adn.png" %}" alt="Logo principal"/>
            </div>
        </div>

        {# Formulario de login #}
        <form class="form" method="POST" action="{% url 'authenticate' %}">
            {# Mensaje de error #}
            {% if error_message %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    {{ error_message }}
                </div>
            {% endif %}

            {# Inputs #}
            {% csrf_token %}
            <input type="text"
                id="username"
                name="username"
                placeholder="Usuario"
            />
            <input type="password"
                id="password"
                name="password"
                placeholder="Contraseña"
            />

            <button type="submit"
                id="boton-login"
                class="btn">
                Entrar
            </button>

            {# Se puede ir a comprar igual #}
            <a href="{% url 'index' %}">
                <p class="margin-top-5">Continuar sin loguearse</p>
            </a>
        </form>
        <footer id="footer">
            <div class="container text-center">
                <span class="text-muted">DSSD 2018</span>
            </div>
        </footer>
     </div>
{% endblock %}

dssd_web/templates/dssd_web/statistics.html
{% extends 'dssd_web/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static "dssd_web/bundles/statistics.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
    {# App principal, renderizada con React #}
    <div id="app-statistics"></div>
{% endblock %}

{% block scripts %}
    {# URLs dinamicas #}
    <script>
        const listSalesURL = "{% url 'dssd_app:list_sales' %}"; {# URL de la informacion de ventas #}
    </script>

    {# Script generado por webpack #}
    <script src="{% static "dssd_web/bundles/statistics.js" %}"></script>
{% endblock %}